### ISSUE TITLE
How to build and use?

### ISSUE THREAD

**Issue by imistyrain** [zhubenfu/License-Plate-Detect-Recognition-via-Deep-Neural-Networks-accuracy-up-to-99.9#1]
Your project looks very great, but there's no useful guide to build it.
I have read the code, but cannot find model_platecar of mtcnn detector model. Any suggestion?

**Comment by zhubenfu** [comment]
License-Plate-Detect-Recognition-via-Deep-Neural-Networks-accuracy-up-to-99.9/ocr_test/plateCard_test/

**Comment by zhubenfu** [comment]
https://github.com/zhubenfu/License-Plate-Detect-Recognition-via-Deep-Neural-Networks-accuracy-up-to-99.9/tree/master/ocr_test/model_platecar

**Comment by rsingh2083** [comment]
> https://github.com/zhubenfu/License-Plate-Detect-Recognition-via-Deep-Neural-Networks-accuracy-up-to-99.9/tree/master/ocr_test/model_platecar

Page not found, please update this link
