### ISSUE TITLE
无法在Windows 8.1 Visual Studio 2015 x64 CUDA环境下编译成功（错误代码：MSB3721）

### ISSUE THREAD

**Issue by jerrychong25** [zhubenfu/License-Plate-Detect-Recognition-via-Deep-Neural-Networks-accuracy-up-to-99.9#17]
你好，

我想试看楼主代码的效果，但是无法在**Windows 8.1 Visual Studio 2015 x64 CUDA**环境下编译成功。

所以，无法达到第九步来启动ocr_test.ext进行测试，便已经在VS2015内有MSB3721错误，如下图：
![image](https://user-images.githubusercontent.com/15714095/53698024-636e0980-3e12-11e9-8f15-b78beca418ca.png)

我的Project路径在：
_D:\GitHub\ALPR\License-Plate-Detect-Recognition-via-Deep-Neural-Networks-accuracy-up-to-99.9-master\caffe-vsproj\_

我的第三方库路径在：
_D:\GitHub\ALPR\License-Plate-Detect-Recognition-via-Deep-Neural-Networks-accuracy-up-to-99.9-master\caffe-vsproj\3rdparty20180726\_

**Visual Studio 2015 Project Compilation MSB3721 Error Log （在附件内）：**
[Visual Studio 2015 Project Compilation Error MSB3721 Log.txt](https://github.com/zhubenfu/License-Plate-Detect-Recognition-via-Deep-Neural-Networks-accuracy-up-to-99.9/files/2923329/Visual.Studio.2015.Project.Compilation.Error.MSB3721.Log.txt)

想请问这个问题该如何解决呢？

谢谢！

**Comment by jerrychong25** [comment]
请问有任何消息吗？

谢谢！

**Comment by zhubenfu** [comment]
参考百度云里面的第三方库，库和cuda版本对应

**Comment by zhubenfu** [comment]
https://github.com/zhubenfu/License-Plate-Detect-Recognition-via-Deep-Neural-Networks-accuracy-up-to-99.9/issues/13

**Comment by jerrychong25** [comment]
> 参考百度云里面的第三方库，库和cuda版本对应

百度云(https://pan.baidu.com/s/1kZDZ98-EZr90hQt_NU-jjA)无法查看，有以下错误：

<img width="919" alt="Screenshot 2019-05-10 at 8 59 42 AM" src="https://user-images.githubusercontent.com/15714095/57495705-f8551d80-7301-11e9-9118-d920081165cc.png">

**Comment by Mebigger** [comment]
请问你编译成功了吗

**Comment by jerrychong25** [comment]
> 请问你编译成功了吗

没有

**Comment by jerrychong25** [comment]
本人关闭此问题，因为已经采用其他方案了。
